
# 取得用戶資料
GET http://localhost:8000/api/user HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|zRH0TzicH6A6iKCzBb6aOQahdBXF3YyFsuYCg9VQ594a61bf

###

# 取得用戶令牌
POST http://localhost:8000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "miles@email.com",
    "password": "password",
    "device_name": "web"
}


###

# 撤銷用戶令牌

DELETE http://localhost:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|zRH0TzicH6A6iKCzBb6aOQahdBXF3YyFsuYCg9VQ594a61bf

###

# 取得用戶資料

GET http://localhost:8000/api/me HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|zRH0TzicH6A6iKCzBb6aOQahdBXF3YyFsuYCg9VQ594a61bf

###

# 取得Todo列表

GET http://localhost:8000/api/todos?page=1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|zRH0TzicH6A6iKCzBb6aOQahdBXF3YyFsuYCg9VQ594a61bf

###

# 取得Todo

GET http://localhost:8000/api/todos/70 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|zRH0TzicH6A6iKCzBb6aOQahdBXF3YyFsuYCg9VQ594a61bf

###

# 刪除Todo

DELETE http://localhost:8000/api/todos/70 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|zRH0TzicH6A6iKCzBb6aOQahdBXF3YyFsuYCg9VQ594a61bf

###

# 更新Todo

PATCH  http://localhost:8000/api/todos/155 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|zRH0TzicH6A6iKCzBb6aOQahdBXF3YyFsuYCg9VQ594a61bf

{
    "name": "wawa2",
    "completed_at": "2022-11-11 11:11:11"
}

###

# 新增Todo

POST  http://localhost:8000/api/todos HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 51|zRH0TzicH6A6iKCzBb6aOQahdBXF3YyFsuYCg9VQ594a61bf

{
    "name": "wawa2",
    "completed_at": "2022-11-11 11:11:11"
}
